[versions]
koin = "4.0.0"
kotlin = "2.0.20"

[libraries]
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
