name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: null2264/actions/gradle-setup@a4d662095a2f2af1ed24f1228eb6e55b0f9f1f29
        with:
          java: 17
          distro: adopt

      - name: Build app
        run: ./gradlew publishToMavenLocal
